pzavolinsky/ts-unused-exports

- src/parser.ts
Fixes https://github.com/pzavolinsky/ts-unused-exports/issues/12
(Can we outsource this work? I'm sure many other TS libraries do the same…)
> Add support for .js file extensions

- lib/cli.js
- src/cli.ts
[#35](https://github.com/pzavolinsky/ts-unused-exports/issues/35)
> Remove line returning number of files via process.exit 

- CHANGELOG.md
- package-lock.json
- package.json
Update **TypeScript** dependency to 3.6.4
- tested on large codebase (~150k lines) - no observed difference in behavior
- solves #33
> Update TypeScript dependency to 3.6.4

- .npmignore
- .nycrc
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- CHANGELOG.md
- bin/ts-unused-exports
- features/base-url.feature
- features/cli.feature
- features/export-statements.feature
- features/files.feature
- features/index.feature
- features/misc.feature
- features/star.feature
- src/analyzer.ts
- src/argsParser.ts
- src/cli.ts
- src/parser.ts
- src/test.ts
- src/usage.ts
- tsconfig.json
(we should put this in a `CONTRIB.md` or similar).
To debug with VSCode make sure you run the following in a terminal:
```
npm run watch
```
Back in VSCode, open a file, put a breakpoint (`F9`), then open a `.feature` file, put the cursor over a `Scenario: ` line and press `F5`.
If you don't know where to put the breakpoint, you can always put it in the first line of the `default` export of `app.ts`.
> Code coverage and debug improvements.

- .nycrc
- .travis.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Add some more badges that seem useful: [#73]
- code coverage
- dependencies state
- npm version
- downloads
- license
Looks like this:
ALSO adds `node 12` to the list of Node versions to run by Travis.
> Add more badges

- .nycrc
- .travis.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
The same PR again, only set up to merge to master.
(when I rebased https://github.com/pzavolinsky/ts-unused-exports/pull/77 I forget to edit the PR to point to master, so that got merged into old branch `add/code-coverage`.)
> Add more badges - merge to master

- package-lock.json
- package.json
- src/cli.ts
- src/test.ts
> Update to chalk 3

- CHANGELOG.md
- features/exported-default-as.feature
- features/exported-function.feature
- src/parser/export.ts
- src/parser/index.ts
Handle the alias from 'export default as x'.
Fixes #28
> Handle 'export default as x'

- example/absolute-paths-2-tsconfigs/package-lock.json
- example/absolute-paths-2-tsconfigs/package.json
- example/absolute-paths-2-tsconfigs/project/project-1/src/app.ts
- example/absolute-paths-2-tsconfigs/project/project-1/tsconfig.json
- example/absolute-paths-2-tsconfigs/src/config/components/MyComponent.ts
- example/absolute-paths-2-tsconfigs/tsconfig.json
- example/absolute-paths-simple/package-lock.json
- example/absolute-paths-simple/package.json
- example/absolute-paths-simple/src/components/MyComponent.ts
- example/absolute-paths-simple/src/components/UnusedComponent.ts
- example/absolute-paths-simple/src/main.ts
- example/absolute-paths-simple/tsconfig.json
- features/export-array.feature
- features/import-absolute-paths.feature
- features/import-alias.feature
- features/star.feature
- ispec/run.sh
- src/analyzer.ts
Add tests for absolute paths and for aliases.
> Add tests for absolute paths and aliases

- .vscode/settings.json
- CHANGELOG.md
- README.md
- features/skip-interface-or-type.feature
- src/argsParser.ts
- src/parser/export.ts
- src/parser/index.ts
- src/types.ts
- src/usage.ts
feature: Add option `--allowUnusedTypes` to skip unused types or interfaces.
Addresses #95
> Add option --allowUnusedTypes to skip unused types or interfaces.

- CHANGELOG.md
- features/export-statements.feature
- src/parser/export.ts
Fix destructured export when involves renaming.
A new PR with commit from @ksr79  -  this PR is created, to workaround a travis issue.
original PR: #125
> Fix: Destructured exports with renaming 2

- CHANGELOG.md
- features/include-dynamic-imports.tsx.feature
- src/parser/dynamic.ts
Fix when dynamic import has curly braces around param
Fixes #147
> Fix when dynamic import has curly braces around param

- CHANGELOG.md
> Update CHANGELOG.md - add missing entries for 7.0.0

- CONTRIBUTING.md
Adjust contrib to make squash optional. 
Fixes #182
> Adjust contrib to make squash optional. Fixes #182

- CHANGELOG.md
- src/parser/import.ts
Fix path separators on windows pr 188
- to get around travis issue, this PR replaces #188
> Fix path separators on windows

- README.md
> docs: Update README with link to eslint plugin

- .github/workflows/node.js.yml
Run CI for PRs, by running both for pull and push with master branch.
ref:
- https://github.com/backdrop-contrib/bee/commit/5bd12eb11a60adbe41aab7f4ff27181c8a12dc85
- https://stackoverflow.com/questions/70767090/github-actions-on-push-and-on-pull-request-difference#:~:text=In%20general%2C%20push%20will%20trigger,from%20a%20fork%20for%20example.
> Run CI on both pull and push with master

- README.md
Minor fixes to README:
- Remove dead eslint tool from README. 
- Remove dead dependencies badge.
> Remove dead tool from README. Remove dead dependencies badge.

- .github/workflows/node.js.deploy.yml
- .github/workflows/node.js.yml
- add the manual trigger
- rename build steps for clarity
> Fix the new manual workflow

- .github/workflows/node.js.deploy.yml
- .github/workflows/node.js.yml
- package.json
- Optimize the matrix of node+TS
- Make the tests workflow reusable.
- Deploy with TS 4.0.5 once again, reusing the tests workflow.
> Optimize builds + release with TS 4.0.5 once more

- .github/workflows/node.js.deploy.yml
- Fix Deploy after the build re-use
- Deploy: replace env with matrix
> Fix Deploy after the build re-use

- CHANGELOG.md
- ispec/_run_from_directory_not_project.sh
- ispec/run.sh
- src/app.ts
- src/cli.ts
Allow run from outside the project directory. Fixes #248
> Allow run from outside the project directory. Fixes #248

- CHANGELOG.md
- example/simple-es5-js/app.ts
- example/simple-es5-js/execute.sh
- example/simple-es5-js/math.ts
- example/simple-es5-js/tsconfig.json
- example/simple-es5-js/unused.ts
- example/simple-es6/app.ts
- example/simple-es6/execute.sh
- example/simple-es6/math.ts
- example/simple-es6/package-lock.json
- example/simple-es6/package.json
- example/simple-es6/tsconfig.json
- example/simple-es6/unused.ts
- example/simple/execute.sh
- example/simple/tsconfig.json
- features/import-alias.feature
- features/star.feature
- package.json
- src/analyzer.ts
- src/parser/import.ts
- src/parser/util.ts
> Add .js extension support with es6 example

- CHANGELOG.md
- example/library-usage-via-TypeScript/execute.sh
- example/library-usage-via-TypeScript/package.json
Fix the example using as library via TypeScript
> Fix the example using as library via TypeScript
