pzavolinsky/ts-unused-exports

lib/parser.js, spec/app-spec.js, spec/data/exports.ts, spec/data/import-e.ts, spec/data/mod-dir-ts/exports.ts, spec/data/mod-dir-tsx/exports.tsx, spec/import-spec.js, src/parser.ts
The current implementation asumes all export declarations are used only
for reexporting things from other modules (export-from-import). Export
declarations are also used to export things declared in the same module.
This pattern is called [Export Statements](https://www.typescriptlang.org/docs/handbook/modules.html#export-statements).
This PR adds support for export-statements, so that they are not
ignored by ts-unused-exports.
Feel free to rewrite everything to your taste.
=> Add support for export statements

lib/cli.js, src/cli.ts
Exit codes are a single byte so anything greater than 255 is going to be modula 256. This patch caps the exit code at 255 so if you have 1000 errant files then you'll still just get 255 as the exit code.
Otherwise if you have an exact multiple of 256 it'll incorrectly return a success exit code:
```sh
$ node -e 'process.exit(256)' ; echo $?
0
```
=> Limit exit code to 255 even if errant file length exceeds that

README.md, example/math.ts, lib/parser.js, spec/data/exports.ts, src/parser.ts
This PR adds a comment flag to ignore certain exports just like the TSLint comment flags. 
```ts
// ts-unused-exports:disable-next-line
export function add2(x:number) { return x + 2; }
```
=> Add comment flag to ignore some exports

CHANGELOG.md, example/tsx/package-lock.json, example/with-paths/app.ts, example/with-paths/math.ts, example/with-paths/package-lock.json, example/with-paths/package.json, example/with-paths/tsconfig.json, example/with-paths/utils/src/calculations.ts, example/with-paths/utils/src/index.ts, example/with-paths/utils/src/to-ignore.ts, ispec/_run-and-check-exit-code.sh, ispec/run.sh, spec/import-spec.js, src/analyzer.ts, src/app.ts, src/argsParser.ts, src/cli.ts, src/deps.ts, src/parser.ts
- Fix the ignorePaths option #55 (it was filtering the parsed files, instead of filtering the end-results)
- Add a test example, that is executed as part of the itests
- Also includes a fix for the `tsx` example
=> Fix the ignorePaths option and add a test example

CHANGELOG.md, README.md, ispec/_run-and-check-exit-code.sh, spec/app-spec.js, spec/import-spec.js, src/analyzer.ts, src/argsParser.ts, src/cli.ts, src/parser.ts, src/types.ts, src/usage.ts
Add  a command line option to include the location within the file, in the output (#57).
This speeds up finding the unused exports, as the IDE will navigate to the correct line in the file.
=> Show locations in files

CHANGELOG.md, src/analyzer.ts
Fixes a bug that was introduced with the `showLineNumber` option.
Issue #61
It was found when using `ts-unused-exports` on a large project.
=> Fix bug introduced with showLineNumber option.

CHANGELOG.md, src/cli.ts
Limit the max exit code when --exitWithCount option is used.
Fixes #79
=> Limit max exit code when --exitWithCount option is used

README.md
Fix minor issues in the readme: [#72]
- typo specif thyem
- add subsections for exit code, list of files
- remove path to folder on Sean's machine
=> Fix minor issues in readme

CHANGELOG.md, README.md, features/export-statements.feature, features/include-definition-files.feature, src/app.ts, src/argsParser.ts, src/parser.ts, src/types.ts, src/usage.ts
By default, include definition (`.d.ts`) files when searching for unused exports.
Add option `--excludeDeclarationFiles` to disable that behavior.
Fixes issues:
- #59 - add option --excludeDeclarationFiles
- #29 - add tests to cover this issue which seems to be already fixed - error with "Cannot find .d.ts file in subdirectory".
=> Add option to include definition files

CHANGELOG.md, features/base-url-undefined.feature, features/misc.feature, package-lock.json, package.json, src/analyzer.ts, src/app.ts, src/cli.ts, src/parser/common.ts, src/parser/export.ts, src/parser/import.ts, src/parser/index.ts, src/types.ts
- updates TypeScript to 3.7
- simplifies some code, using the new optional chaining operator `?.`
- simplifies code by defaulting baseUrl to be '.' (with tests added)
=> Update dependencies to TypeScript 3.7 and simplify some code

.vscode/settings.json
Up VS Code settings for saving eslint
else - will be prompted each time the project is opened.
=> Up VS Code settings for saving eslint

CONTRIBUTING.md, README.md
docs: 
- Update contrib about single commit 
- also mention that the project is maintained by volunteers
@pzavolinsky  I thought of mentioning the 'volunteers' part as this is what [fuse-box](https://github.com/fuse-box/fuse-box) do.  Maybe it will help to get more contributors ?
btw this project is just as popular as fuse-box !
=> docs: Update contrib about single commit and volunteering

CHANGELOG.md, features/export-array.feature, src/analyzer.ts
Support exports destructured from array. fixes #31.
@pzavolinsky - think this is 'good to go' - it was pretty straightforward.
=> fix: Support exports destructured from array. fixes #31.

CHANGELOG.md, README.md, example/with-paths/package.json, example/with-paths/utils/src/to-ignore.ts, features/exclude-paths-from-report.feature, features/ignore-imports-from.feature, ispec/_run-and-check-exit-code.sh, src/analyzer.ts, src/argsParser.ts, src/types.ts, src/usage.ts
feature: Add options to ignore imports from tests or other files.
Addresses part of #2 and fixes #98 
The options are:
| Option name               | Description                                                                                                  | Example                             |
| ------------------------- | ------------------------------------------------------------------------------------------------------------ | ----------------------------------- |
| `ignoreFiles`             | Ignore files with filenames that match the given regex. Use this to exclude groups of files - for example test files and their utilities. …
=> feature: Add options to ignore imports from tests or other files.

CHANGELOG.md, features/export-statements.feature, src/parser/export.ts, src/parser/nodeProcessor.ts
Fix to support destructured exports like 'export const { a, b }'
Fixes #119
=> Fix to support destructured exports like 'export const { a, b }'

CHANGELOG.md, features/include-dynamic-imports.feature, src/parser/dynamic.ts
Fix: Handle dynamic imports that use dereferencing.
Example:
```
import("./a").then(A_imported => {
console.log(A_imported.A);
});
```
Fixes #117
=> Fix: Handle dynamic imports that use dereferencing

CHANGELOG.md, features/include-dynamic-imports.feature, src/parser/dynamic.ts
Fixes for detecting unused  dynamic imports:
* fix: Include methods of classes when searching for dynamic imports
* fix: Do not classify other lambdas as using a dynamic import
* fix: Dynamic import with destructuring and renaming
Fixes #124 #123
=> fix: Fixes for detecting unused  dynamic imports

CHANGELOG.md, features/export-statements.feature, src/analyzer.ts
Make analyzer more robust.
Provides path for #132 so at least there is not an exception.
Also adds some tests around `export *`
=> Make analyzer more robust, add export * tests

CHANGELOG.md, CONTRIBUTING.md, features/include-dynamic-imports.feature, features/include-dynamic-imports.tsx.feature, src/parser/dynamic.ts
Fix dynamic parsing with whitespace and also with assigning to a promise
Fixes #139 and Fixes #140
- Fix: Dynamically import with destructuring and less whitespace
- Fix: Dynamically import to a promise (Issue #139)
- Fix: Dynamically import with lambda inside div (Issue #140)
- (Internal) Add dynamic import tests involving ternary operator
=> Fix dynamic parsing with whitespace and also with assigning to a promise

CHANGELOG.md, example/definition-files-absolute-paths/src/components/UnusedComponent.ts, example/definition-files-absolute-paths/src/main.ts, example/definition-files-absolute-paths/src/models.d.ts, example/definition-files-absolute-paths/tsconfig.json, ispec/run.sh, src/parser/import.ts
Uses fix created by @davidparkagoda with a CHANGELOG added.
Replaces the PR #141, PR #150
Summary:
Fixes a bug where there are false positives, if importing from a d.ts file.
This only occurs if tsconfig uses absolute paths (baseUrl) or uses aliases (paths).
=> check for .d.ts files for absolute paths - 2

CHANGELOG.md, example/definition-files-with-paths/src/components/UnusedComponent.ts, example/definition-files-with-paths/src/main.ts, example/definition-files-with-paths/src/utils/some/models.d.ts, example/definition-files-with-paths/tsconfig.json, features/import-with-paths.feature, ispec/run.sh, src/parser/import.ts
Workaround for github/travis issue -> replaces #151
* Fix: false positives if importing from a d.ts file, and tsconfig is set to use aliases (paths).
=> Add patch for declaration files - when importing from d.ts file - aliases

CHANGELOG.md, package-lock.json, package.json, src/analyzer.ts, src/argsParser.ts, src/cli.ts, src/parser/dynamic.ts, src/parser/export.ts, src/parser/import.ts, src/parser/imports-from-namespace.ts, src/parser/index.ts, src/parser/nodeProcessor.ts, src/parser/util.ts, src/test.ts
Chore - up chalk and dev dependencies
note: eslint now makes rule arrow-parens ON by default.
So, the fix for that added parentheses to ALL lambdas.
ref = https://eslint.org/docs/2.0.0/rules/arrow-parens
Otherwise, there is small improvement that avoids a cast.
fixes #170
=> Chore - up chalk and dev dependencies

README.md
Adds a ko-fi donate button, that points to a new ko-fi account I created, especially for ts-unused-exports:
https://ko-fi.com/tsunusedexports
Currently, it is setup to point to my own PayPal account.
BUT any donations will show up in the public feed of ko-fi.
@pzavolinsky hope this is okay? let's see how it goes!
=> Add ko-fi donate button

.github/workflows/node.js.deploy.yml
- make a separate *manually* run github action, to deploy to npm
- rename and clean up the CI github action
- add comments
Contributes to #208 
TODO
- @pzavolinsky would you like to try adding the npm token to the environment? `secrets.NPM_TOKEN`
Then we can try a release ...
=> build: Split out deploy to npm as separate workflow

features/exclude-paths-from-report.feature, src/argsParser.ts
**Problem**
We have a list of several paths that we exclude from a report. Recently someone added a new path and left a trailing semi-colon (i.e. `--excludePathsFromReport=scripts;jobs;`). It turns out this will entirely disable the tool and prevent any results from being output.
**Solution**
Parse out empty or null arguments from being grabbed as args.
Thanks for the tool though, I appreciate it! Now I'm off to fix all the extra exports people introduced in the meantime 😂
=> Stop extra semicolons in exclude paths from preventing results

features/ignore-locally-used.feature, src/parser/nodeProcessor.ts
Annoyingly I don't remember why I included the logic around the parent node kind originally, but I came across some false positives whilst using this with `--ignoreLocallyUsed` in a large codebase today and removing that logic resolves the issue
=> Fix issue with ignoreLocallyUsed
